package sample.entity;
// Generated 16-Oct-2016 15:53:06 by Hibernate Tools 4.3.1



/**
 * Customers generated by hbm2java
 */
public class Customers  implements java.io.Serializable {


     private String username;
     private String pass;
     private String hoten;
     private String gioitinh;
     private String email;
     private Boolean role;

    public Customers() {
    }

	
    public Customers(String username) {
        this.username = username;
    }
    public Customers(String username, String pass, String hoten, String gioitinh, String email, Boolean role) {
       this.username = username;
       this.pass = pass;
       this.hoten = hoten;
       this.gioitinh = gioitinh;
       this.email = email;
       this.role = role;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }
    public String getHoten() {
        return this.hoten;
    }
    
    public void setHoten(String hoten) {
        this.hoten = hoten;
    }
    public String getGioitinh() {
        return this.gioitinh;
    }
    
    public void setGioitinh(String gioitinh) {
        this.gioitinh = gioitinh;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Boolean getRole() {
        return this.role;
    }
    
    public void setRole(Boolean role) {
        this.role = role;
    }




}


